name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Run lint
        working-directory: backend
        run: npm run lint

      - name: Run tests
        working-directory: backend
        run: npm test

      - name: Build Docker image
        run: docker build -t basheerjani0193/service-health-backend:1.0 ./backend

      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push backend image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push basheerjani0193/service-health-backend:1.0

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t basheerjani0193/service-health-frontend:1.0 ./frontend

      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push frontend image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push basheerjani0193/service-health-frontend:1.0
